# Generated by Django 5.0.1 on 2024-11-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_csv', '0002_correspondencias_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Correspondencias',
        ),
    ]
