# Generated by Django 5.0.1 on 2024-11-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_csv', '0005_usuario_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correspondencia',
        ),
    ]
