# Generated by Django 5.0.1 on 2024-11-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_csv', '0006_delete_correspondencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.TextField(max_length=50)),
                ('fechadocumento', models.TextField(max_length=50)),
                ('folio', models.TextField(max_length=50)),
                ('foliooficina', models.TextField(max_length=50)),
                ('remitente', models.TextField(max_length=50)),
                ('tipodocumento', models.TextField(max_length=50)),
                ('detalle', models.TextField(max_length=50)),
                ('destino', models.TextField(max_length=50)),
                ('resolucion', models.TextField(max_length=50)),
                ('fechadespacho', models.TextField(max_length=50)),
            ],
        ),
    ]
