# Generated by Django 5.0.1 on 2024-11-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_csv', '0007_correspondencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
